### ISSUE TITLE
Instagram feed does not seem to work.

### ISSUE THREAD

**Issue by EvansJahja** [stijnsanders/feeder#3]
Adding URL to instagram user leads to "No such feed could be found. Try using https maybe."

I check on the instagram source code and I *can* find graphql section, so it should work.

**Comment by stijnsanders** [comment]
As feeder's "eater.exe" is itself not logged in to Instagram, it could possibly only work on 'public' Instagram profiles. I can suppose Instagram may answer with "feed not found" on non-pulic feeds, just as if the feed really wouldn't exist, since whether a feed exists under a name is subject to privacy.

I currently don't know if there's a (public) way to get the (recent) data of all feeds a certain user (e.g. yourself) is following. There's perhaps something [here,](https://www.instagram.com/developer/endpoints/users/#get_users_media_recent_self) but using the Instagram API is something entirely different than consuming a 'feed' (in RSS or any other form)... So I would suggest to use something different than a feed reader to use Instagram if you want to follow non-public feeds.
